name: Tag Each Commit

on:
  push:
    branches:
      - master # Define the branches to monitor

jobs:
  tag-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Get Commit SHA
        id: get-sha
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ env.COMMIT_SHA }}
        run: |
          git tag "commit-${COMMIT_SHA}"
          git push origin "commit-${COMMIT_SHA}"
