---
name: CI Workflow with Bandit, Terraform, and TFSec

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
         fetch-tags: true
         set-safe-directory: true

      - name: Bandit Check
        uses: jpetrucciani/bandit-check@main

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Format Terraform
        run: terraform fmt -check

      - name: tfsec-pr-commenter
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    

      - name: Taggers and Release
        uses: fischerscode/tagger@v0.2
        with:
          prefix: v
          
          tag: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          
