name: My pipeline
on:
  push:
    branches:
      - master
    

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: PIMPfiction/AutoTagVersionRelease@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}

