name: My pipeline
on:
  push:
    branches:
      - 'master'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
          
      - uses: EasyDesk/action-semver-release@v1
        with:
          prefix: Semantic Version Release Action
          version: v4.0.0
          prerelease: true
          files: |
            LICENSE

