name: Release tag


on: 
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ 1.0.0 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
