name: Create Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The name of the tag to create'
        required: true
        default: 'v1.0.0'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: BrandonStudio/tag-and-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
