name: Release tag



on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ ... }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
